#define SPLIT_OLED_ENABLE
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_MODS_ENABLE
#define SPLIT_WPM_ENABLE

#define OLED_UPDATE_INTERVAL 100
#define OLED_TIMEOUT 10000

#define N_LAYER 3
#define WIN_LAYER 0
#define MAC_LAYER 1
#define GAMING_LAYER 2
